// GENERATED BY COMPUTER, DO NOT EDIT.
typedef unsigned long long INT_PTR, *PINT_PTR;
typedef INT_PTR (*FARPROC)();
typedef void *HMODULE;
extern FARPROC GetProcAddress(HMODULE, const char *);

FARPROC pfn_WinHttpPacJsWorkerMain __attribute__((used));
FARPROC pfn_WinHttpSetSecureLegacyServersAppCompat __attribute__((used));
FARPROC pfn_DllCanUnloadNow __attribute__((used));
FARPROC pfn_DllGetClassObject __attribute__((used));
FARPROC pfn_Private1 __attribute__((used));
FARPROC pfn_SvchostPushServiceGlobals __attribute__((used));
FARPROC pfn_WinHttpAddRequestHeaders __attribute__((used));
FARPROC pfn_WinHttpAddRequestHeadersEx __attribute__((used));
FARPROC pfn_WinHttpAutoProxySvcMain __attribute__((used));
FARPROC pfn_WinHttpCheckPlatform __attribute__((used));
FARPROC pfn_WinHttpCloseHandle __attribute__((used));
FARPROC pfn_WinHttpConnect __attribute__((used));
FARPROC pfn_WinHttpConnectionDeletePolicyEntries __attribute__((used));
FARPROC pfn_WinHttpConnectionDeleteProxyInfo __attribute__((used));
FARPROC pfn_WinHttpConnectionFreeNameList __attribute__((used));
FARPROC pfn_WinHttpConnectionFreeProxyInfo __attribute__((used));
FARPROC pfn_WinHttpConnectionFreeProxyList __attribute__((used));
FARPROC pfn_WinHttpConnectionGetNameList __attribute__((used));
FARPROC pfn_WinHttpConnectionGetProxyInfo __attribute__((used));
FARPROC pfn_WinHttpConnectionGetProxyList __attribute__((used));
FARPROC pfn_WinHttpConnectionSetPolicyEntries __attribute__((used));
FARPROC pfn_WinHttpConnectionSetProxyInfo __attribute__((used));
FARPROC pfn_WinHttpConnectionUpdateIfIndexTable __attribute__((used));
FARPROC pfn_WinHttpCrackUrl __attribute__((used));
FARPROC pfn_WinHttpCreateProxyResolver __attribute__((used));
FARPROC pfn_WinHttpCreateUrl __attribute__((used));
FARPROC pfn_WinHttpDetectAutoProxyConfigUrl __attribute__((used));
FARPROC pfn_WinHttpFreeProxyResult __attribute__((used));
FARPROC pfn_WinHttpFreeProxyResultEx __attribute__((used));
FARPROC pfn_WinHttpFreeProxySettings __attribute__((used));
FARPROC pfn_WinHttpGetDefaultProxyConfiguration __attribute__((used));
FARPROC pfn_WinHttpGetIEProxyConfigForCurrentUser __attribute__((used));
FARPROC pfn_WinHttpGetProxyForUrl __attribute__((used));
FARPROC pfn_WinHttpGetProxyForUrlEx __attribute__((used));
FARPROC pfn_WinHttpGetProxyForUrlEx2 __attribute__((used));
FARPROC pfn_WinHttpGetProxyForUrlHvsi __attribute__((used));
FARPROC pfn_WinHttpGetProxyResult __attribute__((used));
FARPROC pfn_WinHttpGetProxyResultEx __attribute__((used));
FARPROC pfn_WinHttpGetProxySettingsVersion __attribute__((used));
FARPROC pfn_WinHttpGetTunnelSocket __attribute__((used));
FARPROC pfn_WinHttpOpen __attribute__((used));
FARPROC pfn_WinHttpOpenRequest __attribute__((used));
FARPROC pfn_WinHttpProbeConnectivity __attribute__((used));
FARPROC pfn_WinHttpQueryAuthSchemes __attribute__((used));
FARPROC pfn_WinHttpQueryDataAvailable __attribute__((used));
FARPROC pfn_WinHttpQueryHeaders __attribute__((used));
FARPROC pfn_WinHttpQueryOption __attribute__((used));
FARPROC pfn_WinHttpReadData __attribute__((used));
FARPROC pfn_WinHttpReadProxySettings __attribute__((used));
FARPROC pfn_WinHttpReadProxySettingsHvsi __attribute__((used));
FARPROC pfn_WinHttpReceiveResponse __attribute__((used));
FARPROC pfn_WinHttpResetAutoProxy __attribute__((used));
FARPROC pfn_WinHttpSaveProxyCredentials __attribute__((used));
FARPROC pfn_WinHttpSendRequest __attribute__((used));
FARPROC pfn_WinHttpSetCredentials __attribute__((used));
FARPROC pfn_WinHttpSetDefaultProxyConfiguration __attribute__((used));
FARPROC pfn_WinHttpSetOption __attribute__((used));
FARPROC pfn_WinHttpSetProxySettingsPerUser __attribute__((used));
FARPROC pfn_WinHttpSetStatusCallback __attribute__((used));
FARPROC pfn_WinHttpSetTimeouts __attribute__((used));
FARPROC pfn_WinHttpTimeFromSystemTime __attribute__((used));
FARPROC pfn_WinHttpTimeToSystemTime __attribute__((used));
FARPROC pfn_WinHttpWebSocketClose __attribute__((used));
FARPROC pfn_WinHttpWebSocketCompleteUpgrade __attribute__((used));
FARPROC pfn_WinHttpWebSocketQueryCloseStatus __attribute__((used));
FARPROC pfn_WinHttpWebSocketReceive __attribute__((used));
FARPROC pfn_WinHttpWebSocketSend __attribute__((used));
FARPROC pfn_WinHttpWebSocketShutdown __attribute__((used));
FARPROC pfn_WinHttpWriteData __attribute__((used));
FARPROC pfn_WinHttpWriteProxySettings __attribute__((used));

__declspec(naked) __declspec(dllexport) void WinHttpPacJsWorkerMain() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpPacJsWorkerMain(%rip)");
#else
  __asm__("jmp *pfn_WinHttpPacJsWorkerMain");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpSetSecureLegacyServersAppCompat() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpSetSecureLegacyServersAppCompat(%rip)");
#else
  __asm__("jmp *pfn_WinHttpSetSecureLegacyServersAppCompat");
#endif
}
__declspec(naked) __declspec(dllexport) void DllCanUnloadNow() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_DllCanUnloadNow(%rip)");
#else
  __asm__("jmp *pfn_DllCanUnloadNow");
#endif
}
__declspec(naked) __declspec(dllexport) void DllGetClassObject() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_DllGetClassObject(%rip)");
#else
  __asm__("jmp *pfn_DllGetClassObject");
#endif
}
__declspec(naked) __declspec(dllexport) void Private1() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_Private1(%rip)");
#else
  __asm__("jmp *pfn_Private1");
#endif
}
__declspec(naked) __declspec(dllexport) void SvchostPushServiceGlobals() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_SvchostPushServiceGlobals(%rip)");
#else
  __asm__("jmp *pfn_SvchostPushServiceGlobals");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpAddRequestHeaders() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpAddRequestHeaders(%rip)");
#else
  __asm__("jmp *pfn_WinHttpAddRequestHeaders");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpAddRequestHeadersEx() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpAddRequestHeadersEx(%rip)");
#else
  __asm__("jmp *pfn_WinHttpAddRequestHeadersEx");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpAutoProxySvcMain() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpAutoProxySvcMain(%rip)");
#else
  __asm__("jmp *pfn_WinHttpAutoProxySvcMain");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpCheckPlatform() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpCheckPlatform(%rip)");
#else
  __asm__("jmp *pfn_WinHttpCheckPlatform");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpCloseHandle() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpCloseHandle(%rip)");
#else
  __asm__("jmp *pfn_WinHttpCloseHandle");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnect() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnect(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnect");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionDeletePolicyEntries() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionDeletePolicyEntries(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionDeletePolicyEntries");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionDeleteProxyInfo() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionDeleteProxyInfo(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionDeleteProxyInfo");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionFreeNameList() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionFreeNameList(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionFreeNameList");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionFreeProxyInfo() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionFreeProxyInfo(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionFreeProxyInfo");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionFreeProxyList() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionFreeProxyList(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionFreeProxyList");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionGetNameList() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionGetNameList(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionGetNameList");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionGetProxyInfo() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionGetProxyInfo(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionGetProxyInfo");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionGetProxyList() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionGetProxyList(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionGetProxyList");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionSetPolicyEntries() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionSetPolicyEntries(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionSetPolicyEntries");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionSetProxyInfo() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionSetProxyInfo(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionSetProxyInfo");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpConnectionUpdateIfIndexTable() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpConnectionUpdateIfIndexTable(%rip)");
#else
  __asm__("jmp *pfn_WinHttpConnectionUpdateIfIndexTable");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpCrackUrl() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpCrackUrl(%rip)");
#else
  __asm__("jmp *pfn_WinHttpCrackUrl");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpCreateProxyResolver() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpCreateProxyResolver(%rip)");
#else
  __asm__("jmp *pfn_WinHttpCreateProxyResolver");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpCreateUrl() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpCreateUrl(%rip)");
#else
  __asm__("jmp *pfn_WinHttpCreateUrl");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpDetectAutoProxyConfigUrl() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpDetectAutoProxyConfigUrl(%rip)");
#else
  __asm__("jmp *pfn_WinHttpDetectAutoProxyConfigUrl");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpFreeProxyResult() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpFreeProxyResult(%rip)");
#else
  __asm__("jmp *pfn_WinHttpFreeProxyResult");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpFreeProxyResultEx() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpFreeProxyResultEx(%rip)");
#else
  __asm__("jmp *pfn_WinHttpFreeProxyResultEx");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpFreeProxySettings() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpFreeProxySettings(%rip)");
#else
  __asm__("jmp *pfn_WinHttpFreeProxySettings");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpGetDefaultProxyConfiguration() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpGetDefaultProxyConfiguration(%rip)");
#else
  __asm__("jmp *pfn_WinHttpGetDefaultProxyConfiguration");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpGetIEProxyConfigForCurrentUser() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpGetIEProxyConfigForCurrentUser(%rip)");
#else
  __asm__("jmp *pfn_WinHttpGetIEProxyConfigForCurrentUser");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpGetProxyForUrl() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpGetProxyForUrl(%rip)");
#else
  __asm__("jmp *pfn_WinHttpGetProxyForUrl");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpGetProxyForUrlEx() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpGetProxyForUrlEx(%rip)");
#else
  __asm__("jmp *pfn_WinHttpGetProxyForUrlEx");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpGetProxyForUrlEx2() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpGetProxyForUrlEx2(%rip)");
#else
  __asm__("jmp *pfn_WinHttpGetProxyForUrlEx2");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpGetProxyForUrlHvsi() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpGetProxyForUrlHvsi(%rip)");
#else
  __asm__("jmp *pfn_WinHttpGetProxyForUrlHvsi");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpGetProxyResult() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpGetProxyResult(%rip)");
#else
  __asm__("jmp *pfn_WinHttpGetProxyResult");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpGetProxyResultEx() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpGetProxyResultEx(%rip)");
#else
  __asm__("jmp *pfn_WinHttpGetProxyResultEx");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpGetProxySettingsVersion() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpGetProxySettingsVersion(%rip)");
#else
  __asm__("jmp *pfn_WinHttpGetProxySettingsVersion");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpGetTunnelSocket() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpGetTunnelSocket(%rip)");
#else
  __asm__("jmp *pfn_WinHttpGetTunnelSocket");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpOpen() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpOpen(%rip)");
#else
  __asm__("jmp *pfn_WinHttpOpen");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpOpenRequest() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpOpenRequest(%rip)");
#else
  __asm__("jmp *pfn_WinHttpOpenRequest");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpProbeConnectivity() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpProbeConnectivity(%rip)");
#else
  __asm__("jmp *pfn_WinHttpProbeConnectivity");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpQueryAuthSchemes() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpQueryAuthSchemes(%rip)");
#else
  __asm__("jmp *pfn_WinHttpQueryAuthSchemes");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpQueryDataAvailable() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpQueryDataAvailable(%rip)");
#else
  __asm__("jmp *pfn_WinHttpQueryDataAvailable");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpQueryHeaders() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpQueryHeaders(%rip)");
#else
  __asm__("jmp *pfn_WinHttpQueryHeaders");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpQueryOption() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpQueryOption(%rip)");
#else
  __asm__("jmp *pfn_WinHttpQueryOption");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpReadData() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpReadData(%rip)");
#else
  __asm__("jmp *pfn_WinHttpReadData");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpReadProxySettings() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpReadProxySettings(%rip)");
#else
  __asm__("jmp *pfn_WinHttpReadProxySettings");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpReadProxySettingsHvsi() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpReadProxySettingsHvsi(%rip)");
#else
  __asm__("jmp *pfn_WinHttpReadProxySettingsHvsi");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpReceiveResponse() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpReceiveResponse(%rip)");
#else
  __asm__("jmp *pfn_WinHttpReceiveResponse");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpResetAutoProxy() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpResetAutoProxy(%rip)");
#else
  __asm__("jmp *pfn_WinHttpResetAutoProxy");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpSaveProxyCredentials() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpSaveProxyCredentials(%rip)");
#else
  __asm__("jmp *pfn_WinHttpSaveProxyCredentials");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpSendRequest() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpSendRequest(%rip)");
#else
  __asm__("jmp *pfn_WinHttpSendRequest");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpSetCredentials() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpSetCredentials(%rip)");
#else
  __asm__("jmp *pfn_WinHttpSetCredentials");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpSetDefaultProxyConfiguration() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpSetDefaultProxyConfiguration(%rip)");
#else
  __asm__("jmp *pfn_WinHttpSetDefaultProxyConfiguration");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpSetOption() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpSetOption(%rip)");
#else
  __asm__("jmp *pfn_WinHttpSetOption");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpSetProxySettingsPerUser() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpSetProxySettingsPerUser(%rip)");
#else
  __asm__("jmp *pfn_WinHttpSetProxySettingsPerUser");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpSetStatusCallback() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpSetStatusCallback(%rip)");
#else
  __asm__("jmp *pfn_WinHttpSetStatusCallback");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpSetTimeouts() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpSetTimeouts(%rip)");
#else
  __asm__("jmp *pfn_WinHttpSetTimeouts");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpTimeFromSystemTime() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpTimeFromSystemTime(%rip)");
#else
  __asm__("jmp *pfn_WinHttpTimeFromSystemTime");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpTimeToSystemTime() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpTimeToSystemTime(%rip)");
#else
  __asm__("jmp *pfn_WinHttpTimeToSystemTime");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpWebSocketClose() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpWebSocketClose(%rip)");
#else
  __asm__("jmp *pfn_WinHttpWebSocketClose");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpWebSocketCompleteUpgrade() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpWebSocketCompleteUpgrade(%rip)");
#else
  __asm__("jmp *pfn_WinHttpWebSocketCompleteUpgrade");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpWebSocketQueryCloseStatus() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpWebSocketQueryCloseStatus(%rip)");
#else
  __asm__("jmp *pfn_WinHttpWebSocketQueryCloseStatus");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpWebSocketReceive() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpWebSocketReceive(%rip)");
#else
  __asm__("jmp *pfn_WinHttpWebSocketReceive");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpWebSocketSend() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpWebSocketSend(%rip)");
#else
  __asm__("jmp *pfn_WinHttpWebSocketSend");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpWebSocketShutdown() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpWebSocketShutdown(%rip)");
#else
  __asm__("jmp *pfn_WinHttpWebSocketShutdown");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpWriteData() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpWriteData(%rip)");
#else
  __asm__("jmp *pfn_WinHttpWriteData");
#endif
}
__declspec(naked) __declspec(dllexport) void WinHttpWriteProxySettings() {
#if defined(__x86_64__) || defined(_M_X64)
  __asm__("jmp *pfn_WinHttpWriteProxySettings(%rip)");
#else
  __asm__("jmp *pfn_WinHttpWriteProxySettings");
#endif
}

void proxy_importFunctions(void *hModule) {
  pfn_WinHttpPacJsWorkerMain = GetProcAddress(hModule, "WinHttpPacJsWorkerMain");
  pfn_WinHttpSetSecureLegacyServersAppCompat = GetProcAddress(hModule, "WinHttpSetSecureLegacyServersAppCompat");
  pfn_DllCanUnloadNow = GetProcAddress(hModule, "DllCanUnloadNow");
  pfn_DllGetClassObject = GetProcAddress(hModule, "DllGetClassObject");
  pfn_Private1 = GetProcAddress(hModule, "Private1");
  pfn_SvchostPushServiceGlobals = GetProcAddress(hModule, "SvchostPushServiceGlobals");
  pfn_WinHttpAddRequestHeaders = GetProcAddress(hModule, "WinHttpAddRequestHeaders");
  pfn_WinHttpAddRequestHeadersEx = GetProcAddress(hModule, "WinHttpAddRequestHeadersEx");
  pfn_WinHttpAutoProxySvcMain = GetProcAddress(hModule, "WinHttpAutoProxySvcMain");
  pfn_WinHttpCheckPlatform = GetProcAddress(hModule, "WinHttpCheckPlatform");
  pfn_WinHttpCloseHandle = GetProcAddress(hModule, "WinHttpCloseHandle");
  pfn_WinHttpConnect = GetProcAddress(hModule, "WinHttpConnect");
  pfn_WinHttpConnectionDeletePolicyEntries = GetProcAddress(hModule, "WinHttpConnectionDeletePolicyEntries");
  pfn_WinHttpConnectionDeleteProxyInfo = GetProcAddress(hModule, "WinHttpConnectionDeleteProxyInfo");
  pfn_WinHttpConnectionFreeNameList = GetProcAddress(hModule, "WinHttpConnectionFreeNameList");
  pfn_WinHttpConnectionFreeProxyInfo = GetProcAddress(hModule, "WinHttpConnectionFreeProxyInfo");
  pfn_WinHttpConnectionFreeProxyList = GetProcAddress(hModule, "WinHttpConnectionFreeProxyList");
  pfn_WinHttpConnectionGetNameList = GetProcAddress(hModule, "WinHttpConnectionGetNameList");
  pfn_WinHttpConnectionGetProxyInfo = GetProcAddress(hModule, "WinHttpConnectionGetProxyInfo");
  pfn_WinHttpConnectionGetProxyList = GetProcAddress(hModule, "WinHttpConnectionGetProxyList");
  pfn_WinHttpConnectionSetPolicyEntries = GetProcAddress(hModule, "WinHttpConnectionSetPolicyEntries");
  pfn_WinHttpConnectionSetProxyInfo = GetProcAddress(hModule, "WinHttpConnectionSetProxyInfo");
  pfn_WinHttpConnectionUpdateIfIndexTable = GetProcAddress(hModule, "WinHttpConnectionUpdateIfIndexTable");
  pfn_WinHttpCrackUrl = GetProcAddress(hModule, "WinHttpCrackUrl");
  pfn_WinHttpCreateProxyResolver = GetProcAddress(hModule, "WinHttpCreateProxyResolver");
  pfn_WinHttpCreateUrl = GetProcAddress(hModule, "WinHttpCreateUrl");
  pfn_WinHttpDetectAutoProxyConfigUrl = GetProcAddress(hModule, "WinHttpDetectAutoProxyConfigUrl");
  pfn_WinHttpFreeProxyResult = GetProcAddress(hModule, "WinHttpFreeProxyResult");
  pfn_WinHttpFreeProxyResultEx = GetProcAddress(hModule, "WinHttpFreeProxyResultEx");
  pfn_WinHttpFreeProxySettings = GetProcAddress(hModule, "WinHttpFreeProxySettings");
  pfn_WinHttpGetDefaultProxyConfiguration = GetProcAddress(hModule, "WinHttpGetDefaultProxyConfiguration");
  pfn_WinHttpGetIEProxyConfigForCurrentUser = GetProcAddress(hModule, "WinHttpGetIEProxyConfigForCurrentUser");
  pfn_WinHttpGetProxyForUrl = GetProcAddress(hModule, "WinHttpGetProxyForUrl");
  pfn_WinHttpGetProxyForUrlEx = GetProcAddress(hModule, "WinHttpGetProxyForUrlEx");
  pfn_WinHttpGetProxyForUrlEx2 = GetProcAddress(hModule, "WinHttpGetProxyForUrlEx2");
  pfn_WinHttpGetProxyForUrlHvsi = GetProcAddress(hModule, "WinHttpGetProxyForUrlHvsi");
  pfn_WinHttpGetProxyResult = GetProcAddress(hModule, "WinHttpGetProxyResult");
  pfn_WinHttpGetProxyResultEx = GetProcAddress(hModule, "WinHttpGetProxyResultEx");
  pfn_WinHttpGetProxySettingsVersion = GetProcAddress(hModule, "WinHttpGetProxySettingsVersion");
  pfn_WinHttpGetTunnelSocket = GetProcAddress(hModule, "WinHttpGetTunnelSocket");
  pfn_WinHttpOpen = GetProcAddress(hModule, "WinHttpOpen");
  pfn_WinHttpOpenRequest = GetProcAddress(hModule, "WinHttpOpenRequest");
  pfn_WinHttpProbeConnectivity = GetProcAddress(hModule, "WinHttpProbeConnectivity");
  pfn_WinHttpQueryAuthSchemes = GetProcAddress(hModule, "WinHttpQueryAuthSchemes");
  pfn_WinHttpQueryDataAvailable = GetProcAddress(hModule, "WinHttpQueryDataAvailable");
  pfn_WinHttpQueryHeaders = GetProcAddress(hModule, "WinHttpQueryHeaders");
  pfn_WinHttpQueryOption = GetProcAddress(hModule, "WinHttpQueryOption");
  pfn_WinHttpReadData = GetProcAddress(hModule, "WinHttpReadData");
  pfn_WinHttpReadProxySettings = GetProcAddress(hModule, "WinHttpReadProxySettings");
  pfn_WinHttpReadProxySettingsHvsi = GetProcAddress(hModule, "WinHttpReadProxySettingsHvsi");
  pfn_WinHttpReceiveResponse = GetProcAddress(hModule, "WinHttpReceiveResponse");
  pfn_WinHttpResetAutoProxy = GetProcAddress(hModule, "WinHttpResetAutoProxy");
  pfn_WinHttpSaveProxyCredentials = GetProcAddress(hModule, "WinHttpSaveProxyCredentials");
  pfn_WinHttpSendRequest = GetProcAddress(hModule, "WinHttpSendRequest");
  pfn_WinHttpSetCredentials = GetProcAddress(hModule, "WinHttpSetCredentials");
  pfn_WinHttpSetDefaultProxyConfiguration = GetProcAddress(hModule, "WinHttpSetDefaultProxyConfiguration");
  pfn_WinHttpSetOption = GetProcAddress(hModule, "WinHttpSetOption");
  pfn_WinHttpSetProxySettingsPerUser = GetProcAddress(hModule, "WinHttpSetProxySettingsPerUser");
  pfn_WinHttpSetStatusCallback = GetProcAddress(hModule, "WinHttpSetStatusCallback");
  pfn_WinHttpSetTimeouts = GetProcAddress(hModule, "WinHttpSetTimeouts");
  pfn_WinHttpTimeFromSystemTime = GetProcAddress(hModule, "WinHttpTimeFromSystemTime");
  pfn_WinHttpTimeToSystemTime = GetProcAddress(hModule, "WinHttpTimeToSystemTime");
  pfn_WinHttpWebSocketClose = GetProcAddress(hModule, "WinHttpWebSocketClose");
  pfn_WinHttpWebSocketCompleteUpgrade = GetProcAddress(hModule, "WinHttpWebSocketCompleteUpgrade");
  pfn_WinHttpWebSocketQueryCloseStatus = GetProcAddress(hModule, "WinHttpWebSocketQueryCloseStatus");
  pfn_WinHttpWebSocketReceive = GetProcAddress(hModule, "WinHttpWebSocketReceive");
  pfn_WinHttpWebSocketSend = GetProcAddress(hModule, "WinHttpWebSocketSend");
  pfn_WinHttpWebSocketShutdown = GetProcAddress(hModule, "WinHttpWebSocketShutdown");
  pfn_WinHttpWriteData = GetProcAddress(hModule, "WinHttpWriteData");
  pfn_WinHttpWriteProxySettings = GetProcAddress(hModule, "WinHttpWriteProxySettings");
}
