name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gcc-libs
            mingw-w64-x86_64-binutils


      - name: Generate Vulkan library
        shell: msys2 {0}
        run: |
          cd libraries/vulkan/Lib

          cp /c/Windows/System32/vulkan-1.dll .

          gendef vulkan-1.dll

          dlltool \
            -d vulkan-1.def \
            -D vulkan-1.dll \
            -l libvulkan-1.a


      - name: Build
        shell: msys2 {0}
        run: |
          mingw32-make all


      - name: Check output
        shell: cmd
        run: |
          dir dist


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: winhttp-build
          path: dist/
